export type AppServerProtocolDirection = "client_request" | "server_request" | "server_notification";
export type AppServerProtocolSupport = "handled" | "ignored_safe" | "unsupported_visible" | "candidate" | "not_exposed";
export type AppServerProtocolOwner = "adapter" | "bridge" | "tui" | "future";

export interface AppServerProtocolCapability {
  method: string;
  direction: AppServerProtocolDirection;
  support: AppServerProtocolSupport;
  owner: AppServerProtocolOwner;
}

export const APP_SERVER_PROTOCOL_CAPABILITIES: AppServerProtocolCapability[] = [
  ...cap("client_request", "handled", "adapter", [
    "initialize",
    "thread/start",
    "thread/resume",
    "thread/name/set",
    "thread/goal/set",
    "thread/goal/get",
    "thread/goal/clear",
    "thread/compact/start",
    "thread/read",
    "turn/start",
    "turn/steer",
    "turn/interrupt",
    "model/list",
  ]),
  ...cap("client_request", "candidate", "adapter", [
    "thread/fork",
    "thread/archive",
    "thread/unarchive",
    "thread/rollback",
    "thread/list",
    "thread/turns/list",
    "thread/items/list",
    "modelProvider/capabilities/read",
    "permissionProfile/list",
  ]),
  ...cap("client_request", "not_exposed", "future", [
    "thread/delete",
    "thread/unsubscribe",
    "thread/metadata/update",
    "thread/section/move",
    "thread/shellCommand",
    "thread/approveGuardianDeniedAction",
    "thread/revert",
    "threadSection/list",
    "threadSection/create",
    "threadSection/update",
    "threadSection/delete",
    "thread/loaded/list",
    "thread/inject_items",
    "skills/list",
    "skills/extraRoots/set",
    "hooks/list",
    "marketplace/add",
    "marketplace/remove",
    "marketplace/upgrade",
    "plugin/list",
    "plugin/installed",
    "plugin/reconcile",
    "plugin/read",
    "plugin/skill/read",
    "plugin/share/save",
    "plugin/share/updateTargets",
    "plugin/share/list",
    "plugin/share/checkout",
    "plugin/share/delete",
    "app/read",
    "app/list",
    "app/installed",
    "fs/readFile",
    "fs/writeFile",
    "fs/createDirectory",
    "fs/getMetadata",
    "fs/readDirectory",
    "fs/remove",
    "fs/copy",
    "fs/watch",
    "fs/unwatch",
    "skills/config/write",
    "plugin/install",
    "plugin/uninstall",
    "review/start",
    "experimentalFeature/list",
    "experimentalFeature/enablement/set",
    "mcpServer/oauth/login",
    "config/mcpServer/reload",
    "mcpServerStatus/list",
    "mcpServer/resource/read",
    "mcpServer/tool/call",
    "windowsSandbox/setupStart",
    "windowsSandbox/readiness",
    "account/login/start",
    "account/login/cancel",
    "account/logout",
    "account/rateLimits/read",
    "account/rateLimitResetCredit/consume",
    "account/usage/read",
    "account/workspaceMessages/read",
    "account/sendAddCreditsNudgeEmail",
    "feedback/upload",
    "command/exec",
    "command/exec/write",
    "command/exec/terminate",
    "command/exec/resize",
    "config/read",
    "externalAgentConfig/detect",
    "externalAgentConfig/import",
    "externalAgentConfig/import/recordHistory",
    "externalAgentConfig/import/readHistories",
    "config/value/write",
    "config/batchWrite",
    "configRequirements/read",
    "account/read",
    "getConversationSummary",
    "gitDiffToRemote",
    "getAuthStatus",
    "fuzzyFileSearch",
  ]),

  ...cap("server_request", "handled", "adapter", [
    "item/commandExecution/requestApproval",
    "item/fileChange/requestApproval",
    "item/permissions/requestApproval",
    "applyPatchApproval",
    "execCommandApproval",
    "item/tool/requestUserInput",
  ]),
  ...cap("server_request", "unsupported_visible", "adapter", [
    "mcpServer/elicitation/request",
    "item/tool/call",
    "account/chatgptAuthTokens/refresh",
    "attestation/generate",
  ]),

  ...cap("server_notification", "handled", "adapter", [
    "error",
    "thread/started",
    "thread/archived",
    "thread/deleted",
    "thread/unarchived",
    "thread/closed",
    "thread/name/updated",
    "thread/tokenUsage/updated",
    "turn/started",
    "turn/completed",
    "turn/plan/updated",
    "item/started",
    "item/completed",
    "item/agentMessage/delta",
    "item/plan/delta",
    "item/commandExecution/outputDelta",
    "item/reasoning/summaryTextDelta",
    "item/reasoning/summaryPartAdded",
    "thread/compacted",
    "serverRequest/resolved",
    "model/rerouted",
    "model/verification",
    "model/safetyBuffering/updated",
    "warning",
    "guardianWarning",
    "deprecationNotice",
    "configWarning",
    "windows/worldWritableWarning",
    "thread/status/changed",
    "thread/settings/updated",
  ]),
  ...cap("server_notification", "ignored_safe", "adapter", [
    "thread/goal/updated",
    "thread/goal/cleared",
    "thread/queue/changed",
    "thread/environment/connected",
    "thread/environment/disconnected",
    "project/changed",
    "thread/project/updated",
    "hook/started",
    "hook/completed",
    "turn/diff/updated",
    "item/autoApprovalReview/started",
    "item/autoApprovalReview/completed",
    "autoApprovalReview/strictReviewRequired",
    "rawResponseItem/completed",
    "rawResponse/completed",
    "command/exec/outputDelta",
    "process/outputDelta",
    "process/exited",
    "item/commandExecution/terminalInteraction",
    "item/fileChange/outputDelta",
    "item/fileChange/patchUpdated",
    "item/mcpToolCall/progress",
    "mcpServer/oauthLogin/completed",
    "mcpServer/startupStatus/updated",
    "modelProvider/authRecoveryStarted",
    "modelProvider/authRecoveryCompleted",
    "account/updated",
    "account/rateLimits/updated",
    "app/list/updated",
    "remoteControl/status/changed",
    "externalAgentConfig/import/progress",
    "externalAgentConfig/import/completed",
    "fs/changed",
    "item/reasoning/textDelta",
    "turn/moderationMetadata",
    "fuzzyFileSearch/sessionUpdated",
    "fuzzyFileSearch/sessionCompleted",
    "windowsSandbox/setupCompleted",
    "account/login/completed",
    "skills/changed",
  ]),
  ...cap("server_notification", "not_exposed", "future", [
    "mcpServer/event/stream/notification",
    "thread/realtime/started",
    "thread/realtime/itemAdded",
    "thread/realtime/item/started",
    "thread/realtime/item/transcript/delta",
    "thread/realtime/item/completed",
    "thread/realtime/transcript/delta",
    "thread/realtime/transcript/done",
    "thread/realtime/outputAudio/delta",
    "thread/realtime/sdp",
    "thread/realtime/error",
    "thread/realtime/closed",
  ]),
  ...cap("server_notification", "candidate", "adapter", [
    "thread/reverted",
  ]),
];

function cap(
  direction: AppServerProtocolDirection,
  support: AppServerProtocolSupport,
  owner: AppServerProtocolOwner,
  methods: string[],
): AppServerProtocolCapability[] {
  return methods.map((method) => ({ method, direction, support, owner }));
}
